import os


ABUSEIPDB_API_KEY_PLACEHOLDER = "ABUSEIPDB_API_KEY_PLACEHOLDER"
ABUSEIPDB_API_KEY = os.getenv("ABUSEIPDB_API_KEY", ABUSEIPDB_API_KEY_PLACEHOLDER).strip()


def abuseipdb_api_key_configured():
	return bool(ABUSEIPDB_API_KEY) and ABUSEIPDB_API_KEY != ABUSEIPDB_API_KEY_PLACEHOLDER